---
title: "Homework 9"
author: "LeTicia Cancel"
date: "10/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

packages needed to read Json data
```{r warning=FALSE, message=FALSE}
#install.packages("httr")
#install.packages("rlist")
#install.packages("jsonlite")
#install.packages("pandas")
#install.packages("tidyverse")
#install.packages("ggplot2")
#library(httr)
#ibrary(rlist)
library(jsonlite)
library(dplyr)
library(tidyverse)
library(tibble)
library(ggplot2)
```


Get NY Times API Data
```{r}
resp <- fromJSON("https://api.nytimes.com/svc/search/v2/articlesearch.json?q=Health & Fitness&api-key=AaGWMk26ENauEAKi4AkuhANfJ9PWSGoo")
resp

articles <- resp$response$docs
colnames(articles)

#most shared articles in the past 7 days
mostshared <- fromJSON("https://api.nytimes.com/svc/mostpopular/v2/shared/7.json?api-key=AaGWMk26ENauEAKi4AkuhANfJ9PWSGoo")
result <- mostshared$results
result
```


create tibble of most shared NY Times articles in the past 7 days
```{r}
articles <- as_tibble(result)
articles
```

Visualization of most shared section of the NY Times
```{r}
freq <- articles %>% group_by(section) %>% summarise(counts = n())
freq

ggplot(freq, aes(x = section, y = counts)) + 
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts)) + theme_pubclean()
```

